### ISSUE TITLE
Generate Checkstyle-formatted output from all lint tasks

### ISSUE THREAD

**Issue by hindsholm** [Nykredit/gript#13]
Currently `lint-js` (and `lint-scss`?) generate Checkstyle-formatted output which can be picked up by Jenkins and displayed as a graph.
It would be nice if `lint-ts` and `lint-html` could generate this output as well.

**Comment by jotka** [comment]
ok - it will take a while - the TypeScript linter and html-linter do not contain the XML reporter, so I need to create custom one. I will create those for our project first, and then create pull requests for @JKillian (https://github.com/palantir/tslint) and @mlochbaum (https://github.com/htmllint/htmllint)
