### ISSUE TITLE
consider using the Typings instead of Bower to get TypeScript .ts files

### ISSUE THREAD

**Issue by jotka** [Nykredit/gript#32]
https://github.com/typings/typings
like they do in https://github.com/mgechev/angular2-seed

**Comment by pfrandsen** [comment]
Also used in angular-cli (Angular 2)
https://github.com/angular/angular-cli

**Comment by pfrandsen** [comment]
For TypeScript 2.x this should be done via npm instead of Typings/Bower, see https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by jotka** [comment]
Hi Peter. I will incorporate this in Gript if I manage to find some time beside our current sprint. Thanks for an idea.
