### ISSUE TITLE
Support for building and distribution of bower components

### ISSUE THREAD

**Issue by Mortenagoda** [Nykredit/gript#37]
It would be nice if GRIPT supported build and distribution of bower components. Currently we would have to develop gulp scripts for this purpose in every project.

**Comment by jotka** [comment]
hi @Mortenagoda can you please elaborate on this ? I don't quite get it. Some example of that script would be useful. Thanks :sunglasses:

**Comment by Mortenagoda** [comment]
It should be able to build a bower package much like NIFjs.

**Comment by Mortenagoda** [comment]
Much like maven, GRIPT could build different types of modules. Bower modules could be one, NPM packages another.

GRIPT already run lint, unittests and all that stuff, which should of cause also be run for other types of Javascript/Typescript sources.

The bower build type would probably end up with a target/dist folder (ready for distribution) containing:

- bower.json
- README.md
- lib (folder containing the dist sources)

**Comment by jotka** [comment]
well,  GRIPT is "the basis for the creation of an npm module containing a "complete" Gulp build setup for **an AngularJS application using Sass**". Bower or NPM modules are out of scope of this project IMHO. We don't want to have a huge multi-tool for everyone :smile:
