### ISSUE TITLE
Make tslint.json optional

### ISSUE THREAD

**Issue by pfrandsen** [Nykredit/gript#46]
Lint task should not fail when tslint.json is not present in the project root. Issue a warning instead.

**Comment by jotka** [comment]
Agree, the ts-linter config should not be mandatory for non-typescript projects. Will fix.

**Comment by jotka** [comment]
actually, from now on, Gript will continue with the default rules and issue a warning if any of the linter configuration is missing:

 - .scss-lint.yml
 - .htmllintrc
 - tslint.json
