### ISSUE TITLE
feature: option to specify list of html files that should not be placed in template cache

### ISSUE THREAD

**Issue by pfrandsen** [Nykredit/gript#48]
Certain html cannot be placed in the template cache as they need to be server by the web server.

One example is an oauth2 redirect page. This page will not be used (and thereby loaded) by the application itself - it will be used by an "application" outside of the angular applications control.

Please add an option to specify a list of html files to copy to the dist folder instead of putting them into the template cache.

**Comment by jotka** [comment]
I think that more flexible solution will be that all files ending with  *_tpl.html will be considered as Angular templates and converted to Angular's cache service javascripts. All other HTML files will be just copied into the list structure.

**Comment by pfrandsen** [comment]
That sounds like a good solution. Better to use a naming standard the explicitly specifying.

**Comment by jotka** [comment]
implemented
