### ISSUE TITLE
html-lint doesn't pick up all files

### ISSUE THREAD

**Issue by jotka** [Nykredit/gript#58]
html-linter doesn't pickup all the files from 
```
gulp.src('app/**/*.html')
```

The `ssm-client` project, for example, has a lot of html templates, and HTML files under `app/components` are not being checked for errors. 
It seems that there's a bug in html-linter.  upgrading to 0.7 doesn't help with the issue.
fyi @pfrandsen

**Comment by pfrandsen** [comment]
Thanx for looking into this Jaroslaw.

**Comment by jotka** [comment]
ok, it's not a bug in `html-lint`. It's about not returning a stream in `lint-html` task. Expect a fix today :)

**Comment by jotka** [comment]
taming streams in the morning :) fixed with npm release 0.0.40. Cheers.
