### ISSUE TITLE
Add option to start server without mocks

### ISSUE THREAD

**Issue by pfrandsen** [Nykredit/gript#60]
I you run multiple GRIPT based projects on the same machine you must provide 3 ports for the mock server (stubs, tls, admin) even though you may not use mocks - else you get port conflicts.

P.S. Docker could be a nice solution to get rid of all port conflicts ;-)

**Comment by pfrandsen** [comment]
Probably as simple as adding this to server.gulp.js

    gulp.task('server:nomocks', function () {
        var options = _.merge({}, defaults, gulp.config.server);
        connect.server(options);
    });

**Comment by jotka** [comment]
wouldn't it be better to provide the command line option that would work with all tasks ? (including the default `gulp`, like for example:

- `gulp --nomocks`
- `gulp server --nomocks`

**Comment by pfrandsen** [comment]
Yes - a command line option would be better.

What we have done right now is to add a task that will shift all port by a given command line offset - see doppler-run in our gulp directory. This allows us to run any number of servers at the same time - e.g., nice when you want to run different branches at the same time (of course checked out in different directories ;) )

**Comment by jotka** [comment]
released as 0.0.43, use `--nomocks` when running any task.
