### ISSUE TITLE
Update dependency to PhantomJs

### ISSUE THREAD

**Issue by jhpe** [Nykredit/gript#63]
We are getting errors when using GRIPT's gulp test task to execute tests for AngularJS 1.5.
Some tests fail with GRIPT setup because PhantomJS 1.9.19 does not have `Function.prototype.bind`.
GRIPT should be updated to either use PhantomJS 2.x, or at least a polyfill.

See also https://github.com/angular/angular.js/issues/13794.
Suggestion for polyfill: https://www.npmjs.com/package/phantomjs-polyfill

**Comment by radzikp** [comment]
Fix for PhantomJS 1.x.x: http://stackoverflow.com/questions/28011634/phantomjs-is-not-executing-js

**Comment by jotka** [comment]
published in 0.0.47
