### ISSUE TITLE
Does "gulp prerelease" and "gulp release" work

### ISSUE THREAD

**Issue by langecode** [Nykredit/gript#7]
It seems that the release tasks utilize our internal "gulp-release" module. This module needs to be made available in the npm repositroy. I will push the code from our internal repository into a GitHub repository.

**Comment by jotka** [comment]
thanks for gulp-git-release. I'm including it in the gript 0.0.13.

**Comment by langecode** [comment]
Hehe, you are quick :-)

I have also given you commit right to the gulp-release repository (it should of course be renamed - it turned out that an very old - 2014 - empty gulp module existed with the name gulp-release).

**Comment by langecode** [comment]
btw. how did you get your README.md to display at the npm site? Just removing the README tag from the package.json and it will read the README.md instead? Previously I think is was an required element in the package.json.

**Comment by jotka** [comment]
yes, just remove the readme tag from package.json.
