### ISSUE TITLE
Problem with $templateCache

### ISSUE THREAD

**Issue by Mortenagoda** [Nykredit/gript#77]
Currently I'm trying to implement the Angular2 like component rounter into my project.

https://github.com/angular/router

This eventually changes something inside Angular. My component templates are now loaded from "./"-prefixed url (e.g. "./components/about/about.html") and not just directly from an url without prefix (then "components/about/about.html"). This eventually breaks my tests.

The $templateCache is loaded with:

(function(module) {
    try {
        module = angular.module('MPApp');
    } catch (e) {
    module = angular.module('MPApp', []);
}
module.run(['$templateCache', function($templateCache) {
    $templateCache.put('components/about/about.html',
    '<!DOCTYPE html> {{$ctrl.name}}');
}]);
})();

and the test then fails with because of an unexpected request for "GET ./components/about/about.html":

12 05 2016 16:16:33.107:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
12 05 2016 16:16:33.108:INFO [launcher]: Starting browser PhantomJS
12 05 2016 16:16:34.735:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket /#sdWd5TZ_RDaFnk1_AAAE with id 55560608
WARN: 'Could not instantiate controller', 'AboutController'
PhantomJS 2.1.1 (Windows 7 0.0.0) the about component should render some message FAILED
        Error: Unexpected request: GET ./components/about/about.html
        No more request expected in C:/projects/bp-client-template/bower_components/angular-mocks/angular-mocks.js (line 9)
        $httpBackend@C:/projects/bp-client-template/bower_components/angular-mocks/angular-mocks.js:9:76466
        sendReq@C:/projects/bp-client-template/bower_components/angular/angular.js:9:356517
        serverRequest@C:/projects/bp-client-template/bower_components/angular/angular.js:9:346875
        processQueue@C:/projects/bp-client-template/bower_components/angular/angular.js:9:554262
        C:/projects/bp-client-template/bower_components/angular/angular.js:9:555379
        $eval@C:/projects/bp-client-template/bower_components/angular/angular.js:9:595287
        $digest@C:/projects/bp-client-template/bower_components/angular/angular.js:9:587621
        C:/projects/bp-client-template/target/tmp/js/components/about/about_test.js:17:27

I can think of the following solutions:

- Enable gript configuration for gulp-ng-html2js so the we can add the "./" prefix to the ng-html2js module (https://www.npmjs.com/package/gulp-ng-html2js#optionsprefix).
- Change the ng-html2js template (https://www.npmjs.com/package/gulp-ng-html2js#optionstemplate) to put both the "./" and "" prefixes to the URL.

**Comment by jotka** [comment]
I will expose the config

**Comment by jotka** [comment]
0.0.52
