### ISSUE TITLE
Make app-cache optional and/or configurable

### ISSUE THREAD

**Issue by jensborch** [Nykredit/gript#87]
App-cache is potently dangers to use and an application should be able to disable and/or configure it. See http://alistapart.com/article/application-cache-is-a-douchebag

**Comment by pfrandsen** [comment]
https://www.youtube.com/watch?v=cR-TP6jOSQM
app cache is also in the process of being dropped from the html spec, see e.g. https://html.spec.whatwg.org/multipage/browsers.html#offline or https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

**Comment by jotka** [comment]
it's now configurable.
